// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: server.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCClient interface {
	FwdOnions(ctx context.Context, opts ...grpc.CallOption) (RPC_FwdOnionsClient, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) FwdOnions(ctx context.Context, opts ...grpc.CallOption) (RPC_FwdOnionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RPC_ServiceDesc.Streams[0], "/server.RPC/FwdOnions", opts...)
	if err != nil {
		return nil, err
	}
	x := &rPCFwdOnionsClient{stream}
	return x, nil
}

type RPC_FwdOnionsClient interface {
	Send(*OnionMsg) error
	CloseAndRecv() (*FwdOnionsRes, error)
	grpc.ClientStream
}

type rPCFwdOnionsClient struct {
	grpc.ClientStream
}

func (x *rPCFwdOnionsClient) Send(m *OnionMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rPCFwdOnionsClient) CloseAndRecv() (*FwdOnionsRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FwdOnionsRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility
type RPCServer interface {
	FwdOnions(RPC_FwdOnionsServer) error
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (UnimplementedRPCServer) FwdOnions(RPC_FwdOnionsServer) error {
	return status.Errorf(codes.Unimplemented, "method FwdOnions not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_FwdOnions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RPCServer).FwdOnions(&rPCFwdOnionsServer{stream})
}

type RPC_FwdOnionsServer interface {
	SendAndClose(*FwdOnionsRes) error
	Recv() (*OnionMsg, error)
	grpc.ServerStream
}

type rPCFwdOnionsServer struct {
	grpc.ServerStream
}

func (x *rPCFwdOnionsServer) SendAndClose(m *FwdOnionsRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rPCFwdOnionsServer) Recv() (*OnionMsg, error) {
	m := new(OnionMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FwdOnions",
			Handler:       _RPC_FwdOnions_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
